dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: https://docs.travis-ci.com/user/reference/trusty#Container-based-with-sudo%3A-false
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/box compile

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
- mv bin/trakt-to-yts.phar bin/trakt-to-yts-${TRAVIS_TAG}.phar

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_DEPLOY_KEY
    file: bin/trakt-to-yts-${TRAVIS_TAG}.phar
    skip_cleanup: true
    on:
        repo: pxgamer/trakt-to-yts
        tags: true
        php: '7.1'
