dist: trusty
language: php

php:
  - '7.3'

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - ./trakt-to-yts app:build --build-version ${TRAVIS_TAG:-source}

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: releases
    api_key:
        secure: ${GITHUB_DEPLOY_KEY}
    file: builds/trakt-to-yts.phar
    skip_cleanup: true
    on:
        repo: pxgamer/trakt-to-yts
        tags: true
        php: '7.3'
