dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/box compile

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/box info bin/trakt-to-yts.phar

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_DEPLOY_KEY
    file: bin/trakt-to-yts.phar
    skip_cleanup: true
    on:
        repo: pxgamer/trakt-to-yts
        tags: true
        php: '7.1'
